"use client";

import { useMemo, useState } from "react";

import { useRouter } from "next/navigation";

export type LoadSheetRow = { id: string; date: string; trackingCode: string; pickupInfo: string; deliveryInfo: string; quantity: number; pickupCity: string; deliveryCity: string; weight: number | null; codAmount: number | null; assignedRider?: string | null };
const inputClass = "h-9 rounded-md border border-[#cfd1d4] bg-white px-2.5 text-[13px] text-[#45464b] outline-none focus:border-[#163e6a] focus:ring-2 focus:ring-[#163e6a]/10";

export function LoadSheetTable({ rows, riderId, riders = [] }: { rows: LoadSheetRow[]; riderId?: string; riders?: { id: string; email: string }[] }) {
  const [search, setSearch] = useState("");
  const [pageSize, setPageSize] = useState("10");
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [selectedRiderId, setSelectedRiderId] = useState(riderId ?? "");
  const visibleRows = useMemo(() => {
    const query = search.trim().toLowerCase();
    const filtered = query ? rows.filter((row) => `${row.trackingCode} ${row.pickupInfo} ${row.deliveryInfo} ${row.pickupCity} ${row.deliveryCity}`.toLowerCase().includes(query)) : rows;
    return filtered.slice(0, Number(pageSize));
  }, [pageSize, rows, search]);
  const toggleSelected = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const selectVisible = () => setSelectedIds((current) => Array.from(new Set([...current, ...visibleRows.map((row) => row.id)])));
  const clearVisible = () => setSelectedIds((current) => current.filter((id) => !visibleRows.some((row) => row.id === id)));
  const copyRows = async () => { await navigator.clipboard?.writeText(visibleRows.map((row) => [row.date, row.trackingCode, row.pickupInfo, row.deliveryInfo, row.quantity, row.pickupCity, row.deliveryCity, row.weight ?? "", row.codAmount ?? ""].join("\t")).join("\n")); };
  const downloadCsv = () => { const header = ["Date", "Tracking No", "Pickup Info", "Delivery Info", "Qty", "Pickup City", "Delivery City", "Weight", "COD Amount"]; const body = visibleRows.map((row) => [row.date, row.trackingCode, row.pickupInfo, row.deliveryInfo, row.quantity, row.pickupCity, row.deliveryCity, row.weight ?? "", row.codAmount ?? ""]); const csv = [header, ...body].map((line) => line.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = "load-sheet.csv"; link.click(); URL.revokeObjectURL(link.href); };
  
  const router = useRouter()
  
  const generateLoadSheet = async () => {
    if (!selectedRiderId) return setMessage("Select a rider first.");
    if (!selectedIds.length) return setMessage("Select at least one shipment.");
    setSaving(true); setMessage("");
    try {
      const response = await fetch("/api/account/pickups", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ shipmentIds: selectedIds, assignedToId: selectedRiderId }) });
      const data = await response.json() as { message?: string };
      if (!response.ok) throw new Error(data.message ?? "Could not generate load sheet.");
      router.push(`/account/load-sheets?rider=${encodeURIComponent(selectedRiderId)}`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Could not generate load sheet."); setSaving(false); }
  };
  const printSlip = (row: LoadSheetRow) => {
    const printWindow = window.open("", "_blank", "width=720,height=800");
    if (!printWindow) return;
    const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" } as Record<string, string>)[character] ?? character);
    const value = (input: string | number | null | undefined) => escapeHtml(String(input ?? "—"));
    printWindow.document.write(`<html><head><title>Load sheet ${value(row.trackingCode)}</title><style>
      @page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{margin:0;background:#fff;color:#17191c;font-family:Arial,Helvetica,sans-serif;font-size:12px}.sheet{width:100%;max-width:920px;margin:0 auto;padding:20px 18px}.brand{text-align:center;border-bottom:2px solid #17191c;padding-bottom:10px}.brand img{width:110px;height:auto;object-fit:contain}.brand h1{font-size:24px;margin:7px 0 3px}.brand h2{font-size:15px;margin:0;font-weight:600}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px 32px;margin:18px 0 16px}.meta section{line-height:1.65}.meta section:last-child{text-align:right}.label{display:inline-block;min-width:112px;font-weight:700}.sheet-table{width:100%;border-collapse:collapse;font-size:10px}.sheet-table th,.sheet-table td{border:1px solid #c9cdd2;padding:7px 6px;text-align:left}.sheet-table th{background:#f3f4f5;font-weight:700}.totals{margin-top:12px;border-top:2px solid #17191c}.totals p{margin:0;padding:8px 0;border-bottom:1px solid #17191c;font-weight:700}.signatures{display:flex;justify-content:space-between;margin-top:28px;font-weight:700}.signatures span{display:inline-block;min-width:190px;border-bottom:1px solid #17191c;margin-left:8px}@media print{.sheet{max-width:none;padding:0}}
    </style></head><body><main class="sheet"><header class="brand"><img src="/logo.png" alt="Go Delivery Express" /><h1>Go Delivery Express</h1><h2>Load Sheet Slip</h2></header><div class="meta"><section><div><span class="label">Tracking No:</span>${value(row.trackingCode)}</div><div><span class="label">Pickup:</span>${value(row.pickupInfo)}</div><div><span class="label">Route:</span>${value(row.pickupCity)} → ${value(row.deliveryCity)}</div></section><section><div><span class="label">Date:</span>${value(row.date)}</div><div><span class="label">Rider:</span>${value(row.assignedRider ?? "Pending assignment")}</div><div><span class="label">Slip Type:</span>Individual shipment</div></section></div><table class="sheet-table"><thead><tr><th>S.No</th><th>Tracking No</th><th>Pickup Info</th><th>Delivery Info</th><th>Destination City</th><th>Weight</th><th>Pieces</th><th>COD Amount</th></tr></thead><tbody><tr><td>1</td><td>${value(row.trackingCode)}</td><td>${value(row.pickupInfo)}</td><td>${value(row.deliveryInfo)}</td><td>${value(row.deliveryCity)}</td><td>${row.weight == null ? "—" : `${value(row.weight)} kg`}</td><td>${value(row.quantity)}</td><td>${row.codAmount == null ? "—" : `PKR ${value(row.codAmount)}`}</td></tr></tbody></table><div class="totals"><p>Total No. of Pieces: ${value(row.quantity)}</p><p>Total Weight: ${row.weight == null ? "—" : `${value(row.weight)} kg`}</p><p>COD Amount: ${row.codAmount == null ? "—" : `PKR ${value(row.codAmount)}`}</p></div><div class="signatures"><div>Merchant signature:<span></span></div><div>Rider signature:<span></span></div></div></main><script>window.onload=()=>window.print();</script></body></html>`);
    printWindow.document.close();
  };

  return <div className="mt-5 overflow-hidden rounded-lg border border-[#dedfe2] bg-white shadow-[0_5px_18px_rgba(24,25,30,0.04)]">
    <div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#eeeeef] p-3"><label className="flex items-center gap-2 text-[13px] text-[#686970]">Show <select className={inputClass} value={pageSize} onChange={(event) => setPageSize(event.target.value)}><option>10</option><option>25</option><option>50</option></select> entries</label><div className="flex flex-wrap items-center gap-3">{riders.length > 0 && <label className="flex items-center gap-2 text-[13px] font-semibold text-[#45464b]">Rider <select className={inputClass} value={selectedRiderId} onChange={(event) => setSelectedRiderId(event.target.value)}><option value="">Select Rider</option>{riders.map((rider) => <option key={rider.id} value={rider.id}>{rider.email}</option>)}</select></label>}<label className="flex items-center gap-2 text-[13px] text-[#686970]">Search <input className={`${inputClass} w-56`} value={search} onChange={(event) => setSearch(event.target.value)} /></label><button type="button" onClick={copyRows} className="h-9 rounded-md bg-[#7ac500] px-4 text-[12px] font-semibold text-white">Copy</button><button type="button" className="h-9 rounded-md bg-[#7ac500] px-4 text-[12px] font-semibold text-white" onClick={downloadCsv}>CSV</button><button type="button" className="h-9 rounded-md bg-[#7ac500] px-4 text-[12px] font-semibold text-white" onClick={downloadCsv}>Excel</button>{riders.length > 0 && <button type="button" disabled={saving} onClick={generateLoadSheet} className="h-9 rounded-md bg-[#163e6a] px-4 text-[12px] font-semibold text-white disabled:opacity-50">{saving ? "Generating…" : "Generate load sheet"}</button>}</div>{message && <p className="basis-full m-0 text-right text-[12px] font-semibold text-[#b42318]">{message}</p>}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-270 border-collapse text-left text-[12px] text-[#45464b]"><thead><tr className="bg-[#fafafa] text-[11px] font-bold text-[#55565c]"><th className="w-12 border-b border-r border-[#dedfe2] px-2 py-3 text-center"><input type="checkbox" aria-label="Select all rows" checked={visibleRows.length > 0 && visibleRows.every((row) => selectedIds.includes(row.id))} onChange={(event) => event.target.checked ? selectVisible() : clearVisible()} /></th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Date</th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Tracking No</th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Pickup Info</th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Delivery Info</th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Qty</th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Pickup City</th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Delivery City</th><th className="border-b border-r border-[#dedfe2] px-2 py-3">Weight</th><th className="border-b border-[#dedfe2] px-2 py-3">COD Amount</th><th className="border-b border-[#dedfe2] px-2 py-3">Rider</th><th className="border-b border-[#dedfe2] px-2 py-3">Slip</th></tr></thead><tbody>{visibleRows.length ? visibleRows.map((row) => <tr key={row.id} className="hover:bg-[#f8fbff]"><td className="border-b border-r border-[#eeeeef] px-2 py-3 text-center"><input type="checkbox" aria-label={`Select ${row.trackingCode}`} checked={selectedIds.includes(row.id)} onChange={() => toggleSelected(row.id)} /></td><td className="whitespace-nowrap border-b border-r border-[#eeeeef] px-2 py-3">{row.date}</td><td className="border-b border-r border-[#eeeeef] px-2 py-3 font-mono font-semibold text-[#163e6a]">{row.trackingCode}</td><td className="max-w-55 border-b border-r border-[#eeeeef] px-2 py-3">{row.pickupInfo}</td><td className="max-w-55 border-b border-r border-[#eeeeef] px-2 py-3">{row.deliveryInfo}</td><td className="border-b border-r border-[#eeeeef] px-2 py-3">{row.quantity}</td><td className="border-b border-r border-[#eeeeef] px-2 py-3">{row.pickupCity}</td><td className="border-b border-r border-[#eeeeef] px-2 py-3">{row.deliveryCity}</td><td className="border-b border-r border-[#eeeeef] px-2 py-3">{row.weight == null ? "—" : `${row.weight.toFixed(2)} kg`}</td><td className="border-b border-[#eeeeef] px-2 py-3">{row.codAmount == null ? "—" : `PKR ${row.codAmount.toFixed(2)}`}</td><td className="border-b border-[#eeeeef] px-2 py-3 font-semibold text-[#163e6a]">{row.assignedRider ?? "—"}</td><td className="border-b border-[#eeeeef] px-2 py-3"><button type="button" className="font-semibold text-[#163e6a] hover:text-[#ec8123]" onClick={() => printSlip(row)}>Print</button></td></tr>) : <tr><td colSpan={12} className="py-5 text-center font-semibold text-[#202126]">No data available in table</td></tr>}</tbody></table></div>
    <div className="flex justify-end gap-0 p-3"><button type="button" disabled className="h-9 rounded-l-md border border-[#dedfe2] bg-white px-4 text-[13px] text-[#898a90]">Previous</button><button type="button" disabled className="h-9 rounded-r-md border border-l-0 border-[#dedfe2] bg-white px-4 text-[13px] text-[#898a90]">Next</button></div>
  </div>;
}
